.PHONY: clean All

All:
	@echo "----------Building project:[ 09-Challenge-Pointers - Debug ]----------"
	@cd "09-Challenge-Pointers" && "$(MAKE)" -f  "09-Challenge-Pointers.mk"
clean:
	@echo "----------Cleaning project:[ 09-Challenge-Pointers - Debug ]----------"
	@cd "09-Challenge-Pointers" && "$(MAKE)" -f  "09-Challenge-Pointers.mk" clean
