.PHONY: clean All

All:
	@echo "----------Building project:[ 05-Assignment-Answer - Debug ]----------"
	@cd "05-Assignment-Answer" && "$(MAKE)" -f  "05-Assignment-Answer.mk"
clean:
	@echo "----------Cleaning project:[ 05-Assignment-Answer - Debug ]----------"
	@cd "05-Assignment-Answer" && "$(MAKE)" -f  "05-Assignment-Answer.mk" clean
