.PHONY: clean All

All:
	@echo "----------Building project:[ 15-Challenge-Answer - Debug ]----------"
	@cd "15-Challenge-Answer" && "$(MAKE)" -f  "15-Challenge-Answer.mk"
clean:
	@echo "----------Cleaning project:[ 15-Challenge-Answer - Debug ]----------"
	@cd "15-Challenge-Answer" && "$(MAKE)" -f  "15-Challenge-Answer.mk" clean
