.PHONY: clean All

All:
	@echo "----------Building project:[ 27-Challenge5 - Debug ]----------"
	@cd "27-Challenge5" && "$(MAKE)" -f  "27-Challenge5.mk"
clean:
	@echo "----------Cleaning project:[ 27-Challenge5 - Debug ]----------"
	@cd "27-Challenge5" && "$(MAKE)" -f  "27-Challenge5.mk" clean
