.PHONY: clean All

All:
	@echo "----------Building project:[ 12-Challenge2 - Debug ]----------"
	@cd "12-Challenge2" && "$(MAKE)" -f  "12-Challenge2.mk"
clean:
	@echo "----------Cleaning project:[ 12-Challenge2 - Debug ]----------"
	@cd "12-Challenge2" && "$(MAKE)" -f  "12-Challenge2.mk" clean
