.PHONY: clean All

All:
	@echo "----------Building project:[ 04-Overloading-Operators-Member-Functions - Debug ]----------"
	@cd "04-Overloading-Operators-Member-Functions" && "$(MAKE)" -f  "04-Overloading-Operators-Member-Functions.mk"
clean:
	@echo "----------Cleaning project:[ 04-Overloading-Operators-Member-Functions - Debug ]----------"
	@cd "04-Overloading-Operators-Member-Functions" && "$(MAKE)" -f  "04-Overloading-Operators-Member-Functions.mk" clean
